### ISSUE TITLE
PKHeX freezes when pasting specific Pokémon data via ALM plugin due to possible infinite loop in APILegality.cs

### ISSUE THREAD

**Issue by easyworld** [santacrab2/PKHeX-Plugins#33]
**Describe the bug**  
When using the ALM plugin in PKHeX to paste specific Pokémon data, such as the following:

```
Murkrow (M) @ Eviolite
Level: 1
Shiny: Yes
Ball: Master Ball
Ability: Prankster
Impish Nature
EVs: 252 HP / 0 Atk / 140 Def / 0 SpA / 108 SpD / 10 Spe 
IVs: 31 HP / 0 Atk / 31 Def / 31 SpA / 31 SpD / 31 Spe 
Tera Type: Dark
Language: ChineseS
.CurrentFriendship=0
.Scale=0
.RelearnMoves=$suggestAll
-Taunt
-Haze
-Tailwind
-Foul Play
```

In some cases, PKHeX freezes or becomes unresponsive.

**To Reproduce**  
1. Open PKHeX and load the ALM plugin.
2. Copy showdown data.
3. `Auto-Legality Mod` -> `Import with Auto-Legality Mod`.
4. Observe that PKHeX freezes under certain conditions.

try step 3 two or more times
**Expected behavior**  
The Pokémon data should be processed without freezing, and the user should be able to continue modifying or saving the data.

**Screenshots**  
![image](https://github.com/user-attachments/assets/a3d49442-c9ca-4cc8-a718-796acb6f02ba)
![image](https://github.com/user-attachments/assets/e5637880-3fe2-44b2-aeba-dec1e2ae75d7)

**Additional context**  
- Upon further investigation, it appears that the freezing might be caused by an infinite loop in ALM's code, specifically in the `PKHeX.Core.AutoMod/AutoMod/APILegality.cs` file at line 1257.
- The issue seems to stem from an infinite loop when executing `!criteria.IsIVsCompatibleSpeedLast(ivs, 8)`, which may always return true under certain conditions.
- A possible solution to prevent the infinite loop is to introduce a `count` variable. The loop should continue while `count < 500`; if the count exceeds 500, the loop should terminate to avoid freezing.

**Comment by santacrab2** [comment]
This has been resolved. The issue was that the program wide timeout was not functioning correctly. The loop may look infinite but it should have gotten cancelled by the timeout system. The timeout system was broken with this commit #28  and has been reworked so that the timeout works properly and Blazor developers can still utilize the API.

edit: Just in case you are wondering, your sets illegal because eggs can't inherit masterball, it turns into pokeball.

**Comment by Lusamine** [comment]
> **Additional context**
>     * Upon further investigation, it appears that the freezing might be caused by an infinite loop in ALM's code, specifically in the `PKHeX.Core.AutoMod/AutoMod/APILegality.cs` file at line 1257.
>     * The issue seems to stem from an infinite loop when executing `!criteria.IsIVsCompatibleSpeedLast(ivs, 8)`, which may always return true under certain conditions.
>     * A possible solution to prevent the infinite loop is to introduce a `count` variable. The loop should continue while `count < 500`; if the count exceeds 500, the loop should terminate to avoid freezing.

As for the infinite loop, the issue was two bugs in the BDSP egg RNG generation which caused the random IVs generated each round to not be truly random and reduced the number of perfect IVs that could be copied from the request. That meant there were very few cases where the IV check could pass.

I fixed them [here](https://github.com/santacrab2/PKHeX-Plugins/pull/34) if you want to see how, as well as introducing some other improvements to the code.

Yes, your set was illegal due to ball. Yes, there was a separate issue with the timeout not catching the hang. However, this situation should never have taken so long to hit timeout. Adding a count to the loop as you suggested would be a bandaid that ignores the underlying problem and wouldn't be needed if timeout were working properly. We fixed multiple issues though from this report!
